global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 0.5
   
  width: 50.0
  height: 50.0
  resolution: 0.075
  static_map: true
  origin_x: -20.0
  origin_y: -20.0
   
  rolling_window: false

  map_type: costmap
  origin_z: 0.0
  z_resolution: 1
  z_voxels: 2

  obstacle_range: 2.0
  raytrace_range: 5.0

  publish_voxel_map: false
  transform_tolerance: 1.0
  meter_scoring: true

  footprint: [[-0.42,-0.25],[-0.42,0.25],[0.42,0.25],[0.42,-0.25]]
  #robot_radius: 0.55
  footprint_padding: 0.0

  plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}


  static:        
          map_topic: /map
          subscribe_to_updates: true

  obstacles_layer:
    observation_sources: scan
    scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.0, observation_persistence: 0.2, min_obstacle_height: -1.5, max_obstacle_height: 1.5, obstacle_range: 2.0, raytrace_range: 5.0}

  inflater_layer:
    inflation_radius: 0.6
    cost_scaling_factor: 10.0
