local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 7.5
  publish_frequency: 2.0
  width: 5.5
  height: 5.5
  resolution: 0.015

  rolling_window: true

  map_type: costmap
  origin_z: 0.0
  z_resolution: 1
  z_voxels: 2

  obstacle_range: 2.0
  raytrace_range: 5.0

  publish_voxel_map: false
  transform_tolerance: 1.0
  meter_scoring: true

  footprint: [[-0.42,-0.25],[-0.42,0.25],[0.42,0.25],[0.42,-0.25]]
  footprint_padding: 0.0

  plugins:
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  obstacles_layer:
    observation_sources: scan
    scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.0, observation_persistence: 0.2, min_obstacle_height: -1.5, max_obstacle_height: 1.5, obstacle_range: 2.0, raytrace_range: 5.0}

  inflater_layer:
    inflation_radius: 0.25
    cost_scaling_factor: 10.0
