robot_base_frame: camel_amr_1000_001/base_footprint
transform_tolerance: 0.4
update_frequency: 10.0
publish_frequency: 2.0
# obstacle_range: 6.0
publish_voxel_map: true
navigation_map:
   map_topic: /camel_amr_1000_001/map
obstacles:
  observation_sources:  b_scan_marking b_scan_clearing f_scan_marking f_scan_clearing #points_scan
  b_scan_marking: {
    sensor_frame: camel_amr_1000_001/back_lidar, 
    data_type: LaserScan, 
    topic: /camel_amr_1000_001/back_lidar/scan, 
    marking: true, 
    clearing: false, 
    expected_update_rate: 0.0, 
    observation_persistence: 0.0, 
    min_obstacle_height: 0.0, 
    max_obstacle_height: 2.0, 
    obstacle_range: 5.0,
    raytrace_range: 5.5,
    inf_is_valid: true,
    track_unknown_space: false}
    
  b_scan_clearing:
    {sensor_frame: camel_amr_1000_001/back_lidar, 
    data_type: LaserScan, 
    topic: /camel_amr_1000_001/back_lidar/scan, 
    marking: false, 
    clearing: true, 
    expected_update_rate: 0.0, 
    observation_persistence: 0.0, 
    min_obstacle_height: 0.0, 
    max_obstacle_height: 2.0, 
    obstacle_range: 5.0,
    raytrace_range: 5.5,
    inf_is_valid: true,
    track_unknown_space: false}
  f_scan_marking:
    {sensor_frame: camel_amr_1000_001/front_lidar, 
    data_type: LaserScan, 
    topic: /camel_amr_1000_001/front_lidar/scan, 
    marking: true, 
    clearing: false, 
    expected_update_rate: 0.0, 
    observation_persistence: 0.0, 
    min_obstacle_height: 0.0, 
    max_obstacle_height: 2.0, 
    obstacle_range: 5.0,
    raytrace_range: 5.5,
    inf_is_valid: true,
    track_unknown_space: false}
  f_scan_clearing:
    {sensor_frame: camel_amr_1000_001/front_lidar, 
    data_type: LaserScan, 
    topic: /camel_amr_1000_001/front_lidar/scan, 
    marking: false, 
    clearing: true, 
    expected_update_rate: 0.0, 
    observation_persistence: 0.0, 
    min_obstacle_height: 0.0, 
    max_obstacle_height: 2.0,
    obstacle_range: 5.0,
    raytrace_range: 5.5, 
    inf_is_valid: true,
    track_unknown_space: false}

  points_scan: { 
    data_type: LaserScan, 
    topic: /camel_amr_1000_001/points/scan, 
    marking: true, 
    clearing: true, 
    expected_update_rate: 0.0, 
    observation_persistence: 0.0, 
    min_obstacle_height: 0.0, 
    max_obstacle_height: 0.5,
    obstacle_range: 3.0,
    raytrace_range: 3.5,
    inf_is_valid: true,
    track_unknown_space: false}

virtual_walls_map:
  map_topic: /camel_amr_1000_001/virtual_map
  use_maximum: true
