base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  global_frame_id: camel_amr_1000_001/odom
  
# Robot Configuration Parameters
  max_vel_x: 0.55 #1.17
  min_vel_x: -0.1 #-0.2

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.8 #1.17
  min_vel_trans:  0.1 #-0.2
  
  max_vel_theta: 1.0 #0.3
  min_vel_theta: 0.05 #-0.3
  

  acc_lim_x: 2.5 #0.17
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 #0.1 

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time:  3.0 #4.0 #3.0
  sim_granularity: 0.025 #0.1
  vx_samples: 20 #10 #3
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0
  use_dwa: true


# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0 #24.0
  occdist_scale: 0.02 #5.0 #0.02 
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true